### ISSUE TITLE
UPDATE_APP_TO_LOGIN

### ISSUE THREAD

**Issue by ItsOnlyMyUsername** [Bannerets/tdl#112] opened 2021-12-01 17:56 UTC
Last night, my session crashed, I deleted the folder with it and the next day (today) when I run the script, I get UPDATE_APP_TO_LOGIN (error code: 406).

**Comment by SY573M404** [comment] 2021-12-03 16:10
It means your tdlb version is outdated since Telegram is moving to new API layer 133 (64-bit IDs and sponsored messages). Maybe it will work again if you update tdlib library. I will check this later

**Comment by JesusDR01** [comment] 2021-12-03 19:25
As mentioned in 
https://github.com/tdlib/td/issues/1758#issuecomment-983594142
Telegram updated from 32 to 64 bits, so you need to update td from 1.7.0 to 1.7.9

You have to build td folder (this may help) https://tdlib.github.io/td/build.html?language=JavaScript
And copy all files from td/tdlib/bin/
(libcrypto, libssl, tdjson, zlib)
Where your .js file is located

Remember: you should delete telegramClient folder before execute your script and login with your phone number.

**Comment by ItsOnlyMyUsername** [comment] 2021-12-06 12:08
I did as you wrote above. But now another problem has appeared

{
_: 'error',
code: 400,
message: 'Failed to parse JSON object as TDLib request: unknown class' generateChatInviteLink ''
}

what should i do?

**Comment by Bannerets** [comment] 2021-12-12 11:35
@ItsOnlyMyUsername Your code calls generateChatInviteLink, which no longer exists in TDLib v1.7.9.

**Comment by Bannerets** [comment] 2021-12-12 11:41
It is not possible to log in using a phone number in TDLib v1.7.0 and older versions, so the issue is fixed by updating your TDLib. You can still log in via a QR code in TDLib v1.7.0. Though, tdl's `client.login` doesn't support QR codes.

I've added it to the README.

Prebuilt libtdjson for v1.7.9 is available here: https://github.com/ForNeVeR/tdlib.native/releases

For TypeScript users, the typings in the repository are for TDLib v1.7.0, not v1.7.9. A current workaround is to generate new typings using the `packages/tdlib-types/dist/index.js` generator (develop branch) and replace it in node_modules using [patch-package](https://github.com/ds300/patch-package).

Hopefully TDLib v1.8.0 will be released soon, so we can use the latest tagged version. https://github.com/tdlib/td/issues/1718#issuecomment-953848719

**Closed** 2022-08-27 11:08 UTC
Labels: Type: TDLib Issue
